name: Pull Request Comment Trigger Example
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  rocket:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '/deploy'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: comment PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: |
            Hello @${{ github.event.client_payload.github.actor }}!

            ## List the services you would like to deploy

            - [ ] service1.
            - [ ] service2.
            - [ ] service3.
            - [ ] service4. 
          check_for_duplicate_msg: false
       
